services:
  redis:
    container_name: redis
    image: "redis:alpine"
    restart: always
    ports:
      - 6379:6379
    volumes:
      - cache:/data
    networks:
      - veritas

volumes:
  cache:

networks:
  veritas:
    driver: bridge
