services:
  pgdb:
    container_name: veritas-pgdb
    image: "postgres:alpine"
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - pgdb:/var/lib/postgresql/data
    networks:
      - veritas

  redis:
    container_name: veritas-redis
    image: "redis:alpine"
    restart: always
    ports:
      - 6379:6379
    volumes:
      - cache:/data
    networks:
      - veritas

volumes:
  pgdb:
  cache:

networks:
  veritas:
    driver: bridge
