FROM oven/bun AS build

WORKDIR /app

COPY package.json package.json

COPY bun.lock bun.lock

RUN bun install

COPY . .

RUN bun build \
  --compile \
  --minify-whitespace \
  --minify-syntax \
  --target bun \
  --outfile server \
  ./src/app.ts

FROM gcr.io/distroless/base

WORKDIR /app

COPY --from=build /app/server server

COPY --from=build /app/.env .env

ENV NODE_ENV=production

CMD ["./server"]
EXPOSE 3032
