FROM oven/bun AS build

WORKDIR /app

COPY package.json package.json
COPY bun.lock bun.lock

RUN bun install

COPY . .

RUN bun run build

FROM gcr.io/distroless/base

WORKDIR /app

COPY --from=build /app/build/server server
COPY --from=build /app/.env .env

ENV NODE_ENV=production

CMD ["./server"]

EXPOSE 3032
