service: veritas-server

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1
  architecture: arm64

functions:
  app:
    name: veritas-server
    handler: dist/index.handler
    events:
      - http:
          path: "{proxy+}"
          method: any

package:
  individually: true
  patterns:
    - dist/**
    - "!**/*.ts"
